### ISSUE TITLE
[FEAT]: Last execution watermark file

### ISSUE THREAD

**Issue by fadnincx** [projectpotos/ansible-plays-potos#14]
### Description

A pretask like
```yaml
    - name: Write watermark file
      ansible.builtin.lineinfile:
        regexp: "^ansible_last_{{ runtype }}_run"
        line: "ansible_last_{{ runtype }_run: {{ ansible_date_time.iso8601 }}"
        path: "<somefile>"
        create: True
```

to keep track if they had been executed as intended
